name = "100 things: A single-page Hugo theme"
license = "MIT License"
licenselink = "//github.com/aerohub/hugrid/blob/master/LICENSE.md"
description = "Showcase your progress towards doing something 100 times. Inspired by Visa's [Do 100 Thing](http://www.visakanv.com/blog/100-2/)"
homepage = "//github.com/stealsocks/100-things"
tags = ["responsive", "grid", "simple", "blocks"]
min_version = 0.15

demosite = "https://onehundredsongs.netlify.app"

[author]
  name = "Judah"
  homepage = "//github.com/stealsocks/100-things"
